#easy_admin:
#    entities:
        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
              fields:
                  - id
                  - prenom
                  - nom
                  - username
                  - password
                  - email
                  - { property: 'roles', label: 'Rôles', type: json_array}
            form:
              fields:
                  - email
                  - password
                  - nom
                  - prenom
                  - username
                  - { property: 'roles', label: 'Rôles', type: choice, type_options: {expanded: true, multiple: true, choices: {'Utilisateur':'ROLE_USER', 'Administrateur':'ROLE_ADMIN', 'Commentateur':'ROLE_COMMENTATEUR'}}}
        Article:
            class: App\Entity\Article
        Commentaire:
            class: App\Entity\Commentaire


  